export class SkeletonData {
  static providers = [
    {
      _id: "1",
      name: "تششست",
      nameEn: "ssssffss",
      slug: "",
      coverImage: "data:,",
      logo: "data:,",
    },
    {
      _id: "2",
      name: "تبببست",
      nameEn: "ssssass",
      slug: "",
      coverImage: "data:,",
      logo: "data:,",
    },
    {
      _id: "3",
      name: "تسشت",
      nameEn: "sssss",
      slug: "",
      coverImage: "data:,",
      logo: "data:,",
    },
    {
      _id: "4",
      name: "تیبست",
      nameEn: "ssfsss",
      slug: "",
      coverImage: "data:,",
      logo: "data:,",
    },
  ];

  static categories = [
    { name: "پیش‌غذا", nameEn: "Appetizers", slug: "appetizers" },
    { name: "سالاد", nameEn: "Salads", slug: "salads" },
    { name: "غذای اصلی", nameEn: "Main", slug: "main" },
    { name: "نوشیدنی", nameEn: "Drinks", slug: "drinks" },
    { name: "دسر", nameEn: "Desserts", slug: "desserts" },
    { name: "کباب", nameEn: "Kebab", slug: "kebab" },
    { name: "پیتزا", nameEn: "Pizza", slug: "pizza" },
    { name: "ساندویچ", nameEn: "Sandwich", slug: "sandwich" },
  ];

  static menuItems = [
    {
      _id: "m1",
      name_fa: "آیتم نمونه",
      name_en: "Sample Item",
      description: "توضیحات کوتاه آیتم",
      price: 120000,
      originalPrice: 150000,
      images: ["data:,"] as string[],
      ingredients: ["مواد نمونه ۱", "مواد نمونه ۲"],
      allergens: ["gluten"],
      isSpecialOffer: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      _id: "m2",
      name_fa: "آیتم نمونه",
      name_en: "Sample Item",
      description: "توضیحات کوتاه آیتم",
      price: 95000,
      originalPrice: 0,
      images: ["data:,"] as string[],
      ingredients: ["مواد نمونه ۱", "مواد نمونه ۲"],
      allergens: [],
      isSpecialOffer: false,
      isPopular: false,
      preparationTime: 10,
    },
    {
      _id: "m3",
      name_fa: "آیتم نمونه",
      name_en: "Sample Item",
      description: "توضیحات کوتاه آیتم",
      price: 78000,
      originalPrice: 0,
      images: ["data:,"] as string[],
      ingredients: ["مواد نمونه ۱"],
      allergens: [],
      isSpecialOffer: false,
      isPopular: true,
      preparationTime: 8,
    },
    {
      _id: "m4",
      name_fa: "آیتم نمونه",
      name_en: "Sample Item",
      description: "توضیحات کوتاه آیتم",
      price: 180000,
      originalPrice: 0,
      images: ["data:,"] as string[],
      ingredients: ["مواد نمونه"],
      allergens: [],
      isSpecialOffer: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      _id: "m5",
      name_fa: "آیتم نمونه",
      name_en: "Sample Item",
      description: "توضیحات کوتاه آیتم",
      price: 55000,
      originalPrice: 0,
      images: ["data:,"] as string[],
      ingredients: ["مواد"],
      allergens: [],
      isSpecialOffer: false,
      isPopular: false,
      preparationTime: 5,
    },
  ];
}
