import { ThemeProvider } from "@/providers/theme-provider";
import { AuthProvider } from "@/lib/auth/context";
import type { Metadata } from "next";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const vazirmatn = localFont({
  src: [
    {
      path: "../../public/webfonts/Vazirmatn-RD-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/webfonts/Vazirmatn-RD-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/webfonts/Vazirmatn-RD-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/webfonts/Vazirmatn-RD-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/webfonts/Vazirmatn-RD-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-vazirmatn",
  display: "swap",
});
const AlexandriaBold = localFont({
  src: [
    {
      path: "../../public/webfonts/Alexandria-Bold/Alexandria-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-alexandria-bold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Digital Menu Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
      className={`${AlexandriaBold.variable} ${vazirmatn.variable}`}
    >
      <body
        className={`antialiased min-h-screen bg-background text-foreground`}
        suppressHydrationWarning
      >
        <NextTopLoader showSpinner={false} color="var(--color-primary)" />
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            storageKey="theme"
          >
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
